[2022-06-12 22:27:34,052] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_first_dag.fetch_data_from_predicthq manual__2022-06-12T20:27:27.024916+00:00 [queued]>
[2022-06-12 22:27:34,062] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_first_dag.fetch_data_from_predicthq manual__2022-06-12T20:27:27.024916+00:00 [queued]>
[2022-06-12 22:27:34,063] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 22:27:34,063] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-06-12 22:27:34,063] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 22:27:34,079] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): fetch_data_from_predicthq> on 2022-06-12 20:27:27.024916+00:00
[2022-06-12 22:27:34,081] {standard_task_runner.py:52} INFO - Started process 1897 to run task
[2022-06-12 22:27:34,088] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'fetch_data_from_predicthq', 'manual__2022-06-12T20:27:27.024916+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmphop_gbzr', '--error-file', '/tmp/tmpug48mvxx']
[2022-06-12 22:27:34,088] {standard_task_runner.py:80} INFO - Job 6: Subtask fetch_data_from_predicthq
[2022-06-12 22:27:34,137] {logging_mixin.py:109} INFO - Running <TaskInstance: my_first_dag.fetch_data_from_predicthq manual__2022-06-12T20:27:27.024916+00:00 [running]> on host LAPTOP-M1F9EL62.localdomain
[2022-06-12 22:27:34,197] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=fetch_data_from_predicthq
AIRFLOW_CTX_EXECUTION_DATE=2022-06-12T20:27:27.024916+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-12T20:27:27.024916+00:00
[2022-06-12 22:27:35,457] {logging_mixin.py:109} INFO - Writing here:  /home/leizo/datalake/raw/predicthq/Event/20220612/
[2022-06-12 22:27:35,458] {python.py:175} INFO - Done. Returned value was: None
[2022-06-12 22:27:35,467] {taskinstance.py:1278} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=fetch_data_from_predicthq, execution_date=20220612T202727, start_date=20220612T202734, end_date=20220612T202735
[2022-06-12 22:27:35,506] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-12 22:27:35,546] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
